image: python:latest

before_script:
  - uname -a
  - python -V                                   # Print out python version for debugging

test:
  script:
  - pip install mpi4py
  - mpiexec -n 4 python Hamming.py
