image: python:latest

before_script:
  - uname -a
  - python -V                                   # Print out python version for debugging

test:
  script:
  - apt-get install gcc gcc-fortran wget -y
  - mkdir /nfs
  - cd /nfs
  - wget http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz
#   - apt-get install gcc gcc-fortran kernel-devel  -y
  - tar -xvf mpich-3.1.4.tar.gz 
  - mkdir /nfs/mpich3
  - cd /nfs/mpich-3.1.4
  - ./configure --prefix=/nfs/mpich3
  - make
  - make install
  - pip install mpi4py
  - mpiexec -n 4 python Hamming.py
